# Generated by Django 3.2.9 on 2021-11-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rollNo', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.CharField(choices=[('E', 'EEE'), ('EC', 'ECE'), ('M', 'MEC'), ('I', 'IT'), ('C', 'CSE')], default='EC', max_length=2)),
            ],
        ),
    ]
