# Generated by Django 3.2.9 on 2021-11-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0003_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('EEE', 'EEE'), ('ECE', 'ECE'), ('MEC', 'MEC'), ('IT', 'IT'), ('CSE', 'CSE')], default='ECE', max_length=3),
        ),
    ]
