# Generated by Django 3.2.9 on 2021-11-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0006_auto_20211120_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='branch',
        ),
    ]
