# Generated by Django 3.2.9 on 2021-11-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0007_remove_attendance_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qrApp.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qrApp.branch'),
            preserve_default=False,
        ),
    ]
