# Generated by Django 3.2.9 on 2021-11-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0008_auto_20211120_2010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'branch')},
        ),
    ]
