# Generated by Django 3.2.9 on 2022-02-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0009_alter_subject_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semister',
            field=models.IntegerField(default=1),
        ),
    ]
