# Generated by Django 3.2.9 on 2022-02-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0010_student_semister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='semister',
        ),
        migrations.AddField(
            model_name='attendance',
            name='semister',
            field=models.IntegerField(default=1),
        ),
    ]
