# Generated by Django 3.2.9 on 2022-02-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0011_auto_20220223_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='semister',
            new_name='semester',
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'branch', 'date')},
        ),
    ]
